use_frameworks!

platform :ios, '8.0'

target 'LSJHCategory_Example' do
  pod 'LSJHCategory', :path => '../'

  target 'LSJHCategory_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
